name: agifirst
app:
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "5000"
  ports: "5000"
  build:
    type: dockerfile
    dockerfile: Dockerfile
  context:
    git:
      url: git@github.com:$GITHUB_USER/$GITHUB_REPO.git
      ref: $GITHUB_BRANCH
